name: Deploy to ACR

on:
  workflow_dispatch:
    inputs:
      base_img:
        description: 'Base image'
        required: true
        default: 'ubuntu'
        type: choice
        options:
          - ubuntu
          - centos
      futu_opend_ver:
        description: 'Futu opend version'
        required: true
        default: '7.1.3308'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      REGISTRY_NAME: acrhlbzndpf4bdoo
      IMAGE_NAME: futu-opend-docker
    steps:
      - uses: actions/checkout@master
      - name: inputs
        run: |
          echo "Futu OpenD version: ${{inputs.futu_opend_ver}}"
          echo "Base image: ${{inputs.base_img}}"
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET  }}
      - name: build-push
        uses: docker/build-push-action@v4
        with:
          registry: ${{ env.REGISTRY_NAME }}.azurecr.io
          push: true
          build-args: |
            "FUTU_OPEND_VER=${{ inputs.futu_opend_ver }}"
            "BASE_IMG=${{ inputs.base_img }}"
          tags:
            ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ inputs.base_img }}-${{ inputs.futu_opend_ver }}
